# Generated by Django 5.1.3 on 2025-02-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField(null=True)),
                ("rule_name", models.TextField(null=True)),
                ("sensor_id", models.TextField(null=True)),
                ("content", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RuleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.TextField()),
                ("sensor_id", models.TextField(blank=True, null=True)),
                ("field_name", models.TextField(blank=True, null=True)),
                ("condition", models.TextField(blank=True, null=True)),
                ("thrashold", models.TextField(blank=True, null=True)),
                ("duration", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
