# Generated by Django 5.1.3 on 2025-02-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rulemodel",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="rulemodel",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
